services:
  client:
    image: ${CLIENT_IMAGE:-ghcr.io/brx-hashcode/rabotka-client:latest}
    container_name: rabotka_client_${APP_ENV:-prod}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=hashcode-public"
      - "traefik.http.routers.rabotka-client-${APP_ENV:-prod}.rule=Host(`${CLIENT_DOMAIN}`)"
      - "traefik.http.routers.rabotka-client-${APP_ENV:-prod}.entrypoints=websecure"
      - "traefik.http.routers.rabotka-client-${APP_ENV:-prod}.tls.certresolver=letsencrypt"
      - "traefik.http.services.rabotka-client-${APP_ENV:-prod}.loadbalancer.server.port=${VITE_PORT:-3000}"

networks:
  public:
    name: hashcode-public
    external: true
